### ISSUE TITLE
Don't fail if sources are included

### ISSUE THREAD

**Issue by nikku** [nikku/karma-browserify#52]
If sources are included in the `files` / `preprocessors` section in a `karma.conf.js` karma fails to start with 

```
Chrome 38.0.2125 (Linux) ERROR
  Uncaught Error: Cannot find module '/full/path/to/file.js'
  at /tmp/e23abc7c0b33cd65128e2f9d77ad57525fd1fdbe.browserify:1
```

This looks like a regression (was supposed to work in `karma-bro <= 0.10`.

See #51 and #50.

**Comment by rubenhazelaar** [comment]
Had the same issue. After some digging around the cause seems to be in the browserify version (7.0.3), forced it to work with 8.0.3 and it seems to work properly now. Don't know what the exact reason could be.
